name: SolituderApp
options:
  minimumXcodeGenVersion: 2.44.0
  createIntermediateGroups: true
packages:
  SolituderPackage:
    path: ../..
targets:
  SolituderApp:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: SolituderApp
    info:
      path: SolituderApp/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        NSMicrophoneUsageDescription: Solituder needs microphone access to capture your voice requests while the app is active.
        NSSpeechRecognitionUsageDescription: Solituder uses speech recognition to transcribe your voice input into text prompts.
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.solituder.app
        PRODUCT_NAME: Solituder
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        SWIFT_VERSION: 6.0
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_NSMicrophoneUsageDescription: Solituder needs microphone access to capture your voice requests while the app is active.
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: Solituder uses speech recognition to transcribe your voice input into text prompts.
    dependencies:
      - package: SolituderPackage
        product: SolituderKit
      - sdk: AVFoundation.framework
      - sdk: Speech.framework
      - sdk: UserNotifications.framework
      - sdk: LocalAuthentication.framework
schemes:
  SolituderApp:
    build:
      targets:
        SolituderApp: all
    run:
      config: Debug
    archive:
      config: Release
